testing/linux-next: drop
The package doesn't build right now and is blocking package publishing.
Re-introduce it once we get it building again.

  drivers/tty/vt/conmakehash.c:15:10: fatal error: linux/limits.h: No such file or directory
     15 | #include <linux/limits.h>
        |          ^~~~~~~~~~~~~~~~
  compilation terminated.