kde/qrca: remove
Does not build and nothing depends on it.

src/QrCodeDecoder.cpp:58:14: error: 'class ZXing::DecodeHints' has no member named 'setShouldTryRotate'; did you mean 'setTryRotate'?

Related: https://builds.sr.ht/~postmarketos/job/213157#task-pmbootstrap_build-709