main/postmarketos-base: fix udev rule upgrade
When upgrading from v21.12 to v22.06 or edge, apk will fail with the
following error for samsung-{a3,a5,a7,klte,serranove}:
  ERROR: postmarketos-base-20-r1: trying to overwrite lib/udev/rules.d/20-tm2-touchkey-input.rules owned by device-samsung-a5-8-r0.

This is because 20-tm2-touchkey-input.rules was moved to
postmarketos-base. Set replaces for affected device packages to fix the
error.

Fixes: 9833cc8a ("samsung-{a3,a5,a7,klte,serranove}: move tm2-touchkey rules to pmos-base (MR 2926)")