hybris: remove
glamor-hybris does not build anymore:

In file included from glamor_egl.c:38:
/usr/include/xf86drm.h:40:10: fatal error: drm.h: No such file or directory
   40 | #include <drm.h>
      |          ^~~~~~~
compilation terminated.

hybris-base indirectly depends on this, so remove all of hybris for the
v20.05 branch. If somebody wants to work on adding it again, we can
discuss it; but right now it is too broken.

Related: https://builds.sr.ht/~postmarketos/job/216229#task-pmbootstrap_build-698