device-pine64-pinebookpro: add elogind subpackage (MR 4202)
Move the elogind configuration and post-install call of "loginctl
reload" into an extra subpackage with install_if=elogind.

Fix for:
  Executing device-pine64-pinebookpro-16-r0.post-install
   * service nvme-powersave added to runlevel boot
   * service sysfsconf added to runlevel default
  lib/apk/exec/device-pine64-pinebookpro-16-r0.post-install: line 5: loginctl: not found
  ERROR: device-pine64-pinebookpro-16-r0.post-install: script exited with error 127

Make the post-install scripts more robust while at it, by adding
"exit 0" at the end.

(cherry picked from commit 2d5a9d7d0aca863c1b133b342092e0d9ccd447ee)