main/gcc6: fix build (MR 3153)
Fix the build failure when built with newer gcc:

/home/pmos/build/src/gcc-6.4.0/gcc/config/i386/i386.c: In function 'int function_arg_advance_32(CUMULATIVE_ARGS*, machine_mode, const_tree, long int, long int)':
/home/pmos/build/src/gcc-6.4.0/gcc/config/i386/i386.c:8743:18: error: converting to 'bool' from 'std::nullptr_t' requires direct-initialization [-fpermissive]
 8743 |   bool error_p = NULL;
      |                  ^~~~

Patch source: https://svnweb.freebsd.org/ports/head/lang/gcc7/files/patch-gcc_config_i386_i386.c?view=markup&pathrev=545751

(cherry picked from commit d23fd662f2a1a24d58ed109c69438d327b3b6af8)