CI: add_pmbootstrap_to_import_path: add import (MR 802) (MR 1581)
Fix error on my machine:
	AttributeError: module 'importlib' has no attribute 'util'

(cherry picked from commit 67c0e167d292ab3dfec3bc4768217ec1ed9ec3fb)